### ISSUE TITLE
Auto-draft broken when 'draft' doesn't exist as a post status

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/Edit-Flow#194]
When a user removes the 'draft' post status, any new post they create doesn't get auto-saved properly. For instance, if they open a post, type some content, and close the window, it should still be accessible in the posts list.

Report: http://wordpress.org/support/topic/auto-draft-to-custom-status-default?replies=2#post-4057764

**Comment by justnorris** [comment]
I'm taking a closer look at the issue, here is my take on it - 
WordPress core heavily relies on the draft post status - changing the default post status from "draft" to "pitch" isn't going to work.

I think it makes sense that a draft (a post that hasn't even been saved yet by the author) is not the same as a pitch, even if a pitch is the default post status. 

I see two possible fixes here: 
1. Don't allow users to delete draft post status because it's a core WordPress feature
**or**
2. If a draft status has been deleted, treat auto-saved drafts just like regular drafts in WordPress and take them out of the "Edit Flow" process. In this scenario - there would be no drafts, except for this narrow scenario when the user has started writing a post but hasn't saved it yet. 

I think that fix#2 might be confusing for someone who deletes drafts from post status list. 

Fix#1 would just prevent user from deleting or editing the draft status and make them adjust their workflow around that. 

However, if Fix #1 is implemented - what is going to happen to all the blogs that have already deleted the Draft status? Are there any?

For blogs that have removed the draft status - either one of the fixes is going to be confusing. Either a old auto saves will suddenly show up in the posts lists, or a new "Draft" status will appear even though they've had it deleted for the past 4 years.

**Comment by sboisvert** [comment]
@philipjohn did you mark https://github.com/Automattic/Edit-Flow/issues/194 as high priority?

Personally I'm tempted to say it's a "won't fix".

The only potential "fix" I'd have is to either flag it to end users that there exists "drafts" floating in the ether or what we could do is have some documentation on how people can create a filter to have auto-save posts show up as one of the custom post types. 
I agree with @justnorris that changing the behavior of it now could be problematic / unexpected.

**Comment by philipjohn** [comment]
> Don't allow users to delete draft post status because it's a core WordPress feature

That sounds like the most sensible fix to me. EF has broken core behaviour, so we should fix that.

> what is going to happen to all the blogs that have already deleted the Draft status?

This shouldn't affect existing sites, right, as they've already deleted the draft status. The fix is stopping that from happening again, not retrospectively restoring the draft status.

> a new "Draft" status will appear even though they've had it deleted for the past 4 years.

This shouldn't be the case unless we include a very explicit recreation of the draft status in the fix, which we shouldn't.
