### ISSUE TITLE
TinyMce Conflict with MailPoet newsletter editor

### ISSUE THREAD

**Issue by rafaehlers** [Automattic/Edit-Flow#263]
There's a conflict happening on MailPoet when you enable Edit Flow. Somehow our TinyMCE stop working at all.

This conflict might be happening for more than 6 months: http://wordpress.org/support/topic/mail-poet-former-wysija-newsletter-conflict

MailPoet: http://wordpress.org/plugins/wysija-newsletters/ (any version)
Edit Flow version: 0.8

Video reproducing the issue: https://mailpoet.viewscreencasts.com/95107ca0caf50a002c1860437e48b322

**Comment by iNibori** [comment]
There's a similar issue when using the "Awesome Support" plugin and mailpoet.

TinyMCE will crash and the functionality of editing texts in the newsletter editor is gone.

JS Console errors:
Uncaught module [h] returned undefined (/wp-content/plugins/mailpoet/assets/js/lib/tinymce/themes/modern/theme.min.js)

Uncaught Error: Node cannot be null or undefined (/wp-includes/js/tinymce/tinymce.min.js?ver=4800-20180716)

I'm sadly not able to use mailpoet because of this.
