### ISSUE TITLE
convert_to_screen(), add_meta_box() was called incorrectly?

### ISSUE THREAD

**Issue by VesterDe** [Automattic/Edit-Flow#354]
I get the following error on every front-end page-load. 4 times, specifically, in groups of two.

I've traced the error back to Edit Flow, but since I don't understand it I don't really know what to do with it. Can I ignore it?

`PHP Notice:  convert_to_screen(), add_meta_box() was called <strong>incorrectly</strong>. Likely direct inclusion of wp-admin/includes/template.php in order to use add_meta_box(). This is very wrong. Hook the add_meta_box() call into the add_meta_boxes action instead. Please see <a href="https://codex.wordpress.org/Debugging_in_WordPress">Debugging in WordPress</a> for more information. (This message was added in version 3.3.) in .../wp-includes/functions.php on line 3897`

**Comment by cojennin** [comment]
> I get the following error on every front-end page-load

What version of WordPress and Edit Flow are you running?
Do you still get this notice when you disable all other plugins except Edit Flow?
Do you get this notice when you load admin pages, non-admin pages or both?

**Comment by cojennin** [comment]
Following up on this. Is there any more information you can provide about the issue?

**Comment by VesterDe** [comment]
I'm sorry I haven't given more context, but the project is on hold right
now.

Maybe resolve it for now and I'll write it up when I get back to the work.
ᐧ

------------------------------------------------------------------------
Demjan Vester: LINKED-IN <http://si.linkedin.com/in/vesterde/>
Phone: +386 (0)40 193 536

**Comment by cojennin** [comment]
Sounds good. Closing, feel free to reopen (or create a new issue) when you've got the time. Thanks!

**Comment by felixwahner** [comment]
I've got the same issue:
What version of WordPress and Edit Flow are you running?
- 4.6.1 / 0.8.2
Do you still get this notice when you disable all other plugins except Edit Flow?
- Yes
Do you get this notice when you load admin pages, non-admin pages or both?
- Only on Frontend-Pages

**Comment by cojennin** [comment]
Going to reopen.

@felixwahner what theme are you using? Do you still get the message when you revert to the default [WordPress 2016 theme](https://wordpress.org/themes/twentysixteen/)?

**Comment by felixwahner** [comment]
We're using a custom theme that's written by us from scratch. I've switched to "Twenty Sixteen" and still got the error messages.

**Comment by lorenzrings** [comment]
Hi, we have the same issue. The error message comes in "Twenty Sixteen" and in our own theme.

**Comment by shackep** [comment]
I am getting this same error message as well.
Traced to:
screen-options.php line 85
$screen = convert_to_screen($page); 

The value of $page is "dashboard_page_calendar" which is set as a contstant in calendar.php

 https://developer.wordpress.org/reference/functions/convert_to_screen/ seems to expect a hook.

**Comment by shackep** [comment]
Both 'calendar' and 'story budget' modules set constants that are used by convert_to_screen. When those two sub plugins/modules are disabled the PHP notice goes away.

**Comment by ithakaben** [comment]
This is because WP_Screen must be available before convert_to_screen() is called. Editflow calls the page_to_screen_id() function as part of the WP init action, which takes pace prior to WP_Screen being available. 

This isn't a problem in admin because the admin_init action includes WP_Screen sooner

As a temporary workaround, I've updated the conditional inside page_to_screen_id() from `	if ( function_exists('convert_to_screen') )` to `if ( function_exists('convert_to_screen') && class_exists( 'WP_Screen' ))` - this works fine for how Editflow is used by our site, but if there are major reasons for having screen adjustments on the front end, it can be addressed by wrapping the functions that call page_to_screen_id() in an action that fires after WP_Screen is included.

**Comment by shantanu2704** [comment]
Hey @philipjohn, is there any update on this? I would like to take this up if no one else is working on it

**Comment by justnorris** [comment]
Hey Shantanu - you're welcome to pick this up if you want to!

**Comment by shantanu2704** [comment]
Hey @justnorris  - I've gone through the code and I think we can do this in one of following three ways:

1. Add the conditional `is_admin()` whenever the (wrapper) function `add_screen_options_panel` is called, to avoid `convert_to_screen` being called on the front-end whenever WP `init()` is fired.

2. Along with the call to `add_screen_options_panel` in the `init()` of the modules _calender_ and _story-budget_, there are other calls to functions that are hooked into admin hooks like `admin_init` which is unnecessary when WP `init()` runs in the front-end.

3. Or we could refactor the `init()` method into `init()` and `admin_init()` and have those admin_hooks run only on the back-end instead of them running on both the front-end and the back-end like they are being run right now.

/cc @philipjohn @sboisvert

**Comment by rinatkhaziev** [comment]
@shantanu2704 thanks for the PR! I think option `3` is a better way to go, `is_admin()` check feels workaround-y, screen options are only meant for admin area, so, logically, a better place to run that code is `admin_init`. 

If you're open to make that change, I'll make sure this gets merged into upcoming 0.8.3 release.
