### ISSUE TITLE
i18n: 'Publish' box in Editing view is in English

### ISSUE THREAD

**Issue by achumakov** [Automattic/Edit-Flow#376]
(Just putting here not to forget, maybe will try to fix myself, but unsure)
1. Save/save as button in initially in English, ignoring any localization (though, it turns localized on button press)
2. When choosing publication date at the same box, date format is uninternationalized, as it should do.

A word from @cojennin:

"Yep, a lot of that text gets replaced using Javascript [here](https://github.com/Automattic/Edit-Flow/blob/master/modules/custom-status/lib/custom-status.js#L13). Think we'll need to use [wp_localize_script](https://codex.wordpress.org/Function_Reference/wp_localize_script) to provide the correct translations for the text when [enqueuing the Javascript](https://github.com/Automattic/Edit-Flow/blob/ccd35be0c712450a3e926c91cc3953397bd1a31c/modules/custom-status/custom-status.php#L298).

**Comment by raduconst** [comment]
Hey @achumakov !

1. I fixed this issue through a PR and things should be fine now.

2. Could you give me an example of how things should change on the publication date? I'm asking for some more details because I played with two languages (English and Français) that use different formats and everything is working very well:

_English_:
<img width="274" alt="screen shot 2018-01-17 at 14 35 48" src="https://user-images.githubusercontent.com/6512220/35043088-e7efb18a-fb93-11e7-8798-47c3e848e9c0.png">

_Français_:
<img width="282" alt="screen shot 2018-01-17 at 14 36 04" src="https://user-images.githubusercontent.com/6512220/35043098-ef5a8f94-fb93-11e7-9028-bafba66e0945.png">

**Comment by WPprodigy** [comment]
Closing this for now due to lack of feedback.

Do feel free to re-open if there are further data-related changes needed.
