### ISSUE TITLE
Expensive queries

### ISSUE THREAD

**Issue by philipjohn** [Automattic/Edit-Flow#444]
These queries appear a fair bit on the frontend of sites running Edit Flow:

`SELECT tt.term_id, tt.term_taxonomy_id FROM wp_terms AS t INNER JOIN wp_term_taxonomy as tt ON tt.term_id = t.term_id WHERE t.slug = '?' AND tt.taxonomy = '?' ORDER BY t.term_id ASC LIMIT ?`

They're pretty slow and we should try to speed them up or make them less frequent.

**Comment by sboisvert** [comment]
Do you know what the call stack is for these or what function creates them?

**Comment by cojennin** [comment]
I haven't seen this query on the frontend, there is a `get_terms` call hooked into `init` but it's structured as follows:

```
SELECT t.*, tt.*
FROM wp_terms AS t
INNER JOIN wp_term_taxonomy AS tt
ON t.term_id = tt.term_id
WHERE tt.taxonomy IN ('post_status')
ORDER BY t.name ASC
```

Let me know if that's the one you're referring to (or if you have more details on the query you're looking at) and I'll dig into it a bit more to see if there's anything we can do, otherwise closing this for now, thanks!
