### ISSUE TITLE
Release coming any time soon?

### ISSUE THREAD

**Issue by runofthemill** [Automattic/Edit-Flow#455]
Hey guys!

I just found Edit Flow in the plugin directory, and ended up here. I see a ton of changes have been made since the 0.8.2 release (168 commits to `master`) in Sept. '16 and plenty of recent activity, as well as Issue Milestones for 0.8.3 and 0.9, though those seem untouched recently and don't have any issues tagged to them, so I wanted to find out what state the plugin is in on `master`. Obviously I'm not expecting it to work flawlessly under all scenarios in every version of WP and PHP, but as far as you know is it stable on WP 4.9.5/ PHP 7.x? Do you guys expect to tag a new release anytime soon?

Cheers!

**Comment by rinatkhaziev** [comment]
Hey @runofthemill,

Good news, we're planning to release 0.8.3 in the coming days after some housekeeping work, it will mostly contain the changes you mentioned (168 commits since Sep 16).

To the best of my knowledge, the plugin is stable on latest WordPress and PHP versions. We'll add that information in the new release.

**Comment by runofthemill** [comment]
Thanks @rinatkhaziev! Much appreciated :)
