### ISSUE TITLE
Can't switch between visual or text modes in Wordpress post editor

### ISSUE THREAD

**Issue by AMecea** [Automattic/Edit-Flow#495]
The errors in the console are:
```
TypeError: $ is not a function
```
 at this [line](https://github.com/Automattic/Edit-Flow/blob/19a9680518a9fbcca40495c041529cd6ff461dd5/modules/editorial-comments/lib/editorial-comments.js#L26)

Plugin version: 0.9
Wordpress version: 4.9.9

**Comment by raduconst** [comment]
@AMecea Any chance that you could share some more details about this issue? What's the page that you're viewing when this error is available on the console? I'm asking this because I'm using WP 4.9.9, Edit Flow 0.9 and I'm not seeing this problem. I tried to add a few comments, switch between Visual/Text and everything works fine.

**Comment by AMecea** [comment]
Hi @raduconst, Sorry, but I can't provide any useful information, because the client does not use the plugin anymore. But I think that the plugin was not the whole problem.

 I think you can close this issue. Thanks.
