### ISSUE TITLE
Custom Statuses:  Fatal Error when used with Ninja Shop

### ISSUE THREAD

**Issue by dchymko** [Automattic/Edit-Flow#539]
Discovered when working on #538 / #490 

1. Enable Custom Status Module
2. Install Ninja Shop
3. Go to Ninja Shop -> Add Product

Fatal Error: `Fatal error: Uncaught ArgumentCountError: Too few arguments to function EF_Custom_Status::fix_preview_link_part_three(), 1 passed in /var/www/html/wp-includes/class-wp-hook.php on line 286 and exactly 2 expected in /var/www/html/wp-content/plugins/Edit-Flow/modules/custom-status/custom-status.php on line 1511`

WordPress 5.2.4
PHP 7.2 
EditFlow 0.9
Ninja Shop 1.1.1

**Comment by WPprodigy** [comment]
Hmm, definitely an issue on the Ninja Ship side. Core does pass two args, at least since 4.0.0: https://developer.wordpress.org/reference/hooks/preview_post_link/

The plugin is doing this: https://plugins.trac.wordpress.org/browser/ninja-shop/trunk/lib/products/class.products-post-type.php#L265

```
apply_filters( 'preview_post_link', add_query_arg( 'preview', 'true', $preview_link ) )
```

Unfortunately looks like this plugin is no longer under development, and I'm struggling to find any related repositories. Probably best to just one-off fix this on sites that are using Ninja Shop - the `$post` is readily available for use in that filter where needed.

The other option would be to check if Ninja Shop is active, or more specifically if on the product post type page, and leave off the filter(s) in EF. That does't feel like a good option though.

**Comment by cojennin** [comment]
> Probably best to just one-off fix this on sites that are using Ninja Shop

@WPprodigy This seems like the right move. Will close this for now but if folks have anything else to add, please do.
